name: 'Dependency review and push scan'

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "**" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always

  simple-push-check:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code on push'
        uses: actions/checkout@v4
      - name: 'Echo pushed branch'
        run: echo "Branch ${GITHUB_REF} was pushed."
